<?php
/**
 * Juvi_Press extension
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 * 
 * @category       Juvi
 * @package        Juvi_Press
 * @copyright      Copyright (c) 2016
 * @license        http://opensource.org/licenses/mit-license.php MIT License
 */
/**
 * Press Article link widget template
 *
 * @category    Juvi
 * @package     Juvi_Press
 * @author      Ultimate Module Creator
 */
?>
<?php $_pressarticle = $this->getCurrentPressarticle();?>
<?php if ($_pressarticle) :?>
    <div class="pressarticle-widget-link">
        <a href="<?php echo $_pressarticle->getPressarticleUrl()?>"><?php echo $_pressarticle->getPressArticleTitle()?></a>
    </div>
<?php endif;?>
