<?php
    $products = Mage::getModel('catalog/category')->load(62);
    $productslist = $products->getProductCollection()
        ->setPageSize(10)
        ->addAttributeToSelect('*');
?>

<div class="productscroller">
    <a class="arrow-left product-arrow-l" href="#"></a>
    <a class="arrow-right product-arrow-r" href="#"></a>

    <div class="scroller-container">
        <div class="swiper-wrapper">
            <?php foreach($productslist as $featured_product): ?>
            
            <div class="swiper-slide">
                <div class="product">
                    <a href="<?php echo $featured_product->getProductUrl(); ?>">
                        <img
                            src="<?php echo $this->helper('catalog/image')->init($featured_product, 'thumbnail')->resize(160, 160); ?>"/>

                        <h2 class="product-name"><?php echo $this->stripTags($featured_product->getName(), null, true) ?></h2>
                    </a>
                    <?php if ($featured_product->getFrameLensColour()): ?>
                    <p class="frame-lens-colour"><?php echo $featured_product->getFrameLensColour(); ?></p>
                    <?php endif; ?>
                    <?php echo Mage::helper('core')->currency(Mage::helper('tax')->getPrice($featured_product, $featured_product->getFinalPrice(), 2)); ?>
                    <a class="shop-now"
                       href="<?php echo $featured_product->getProductUrl(); ?>"><?php echo $this->__('Shop Now >') ?></a>
                </div>
            </div>

            <?php endforeach; ?>
        </div>
    </div>
    <div class="product-pagination"></div>
</div>

<script type="text/javascript">
    var mySwiper2 = new Swiper('.scroller-container', {
        loop: false,
        pagination: '.product-pagination',
        paginationClickable: true,
        speed: 1200,
        slidesPerView: 5
    });
    jQuery('.product-arrow-l').on('click', function (e) {
        e.preventDefault()
        mySwiper2.swipePrev()
    });
    jQuery('.product-arrow-r').on('click', function (e) {
        e.preventDefault()
        mySwiper2.swipeNext()
    })
</script>
