<?php

/**
 * @author      Sam Mahoney
 * @copyright   Copyright (C) 2015
 */

?>

<div class="promo-wrapper">
	<div class="promo-box box-a">
		<a href="<?php echo $this->getValue('link_a'); ?>">
			<div class="promo-content">
				<img class="promo-img" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'homepage/'.$this->getValue('image_a') ?>" alt="<?php echo $this->getValue('image_a_alt'); ?>" />
				<div class="content-wrap">
					<?php echo $this->getValue('text_a'); ?>
				</div>
			</div>
		</a>
	</div>
	<div class="promo-box box-b">
		<a href="<?php echo $this->getValue('link_b'); ?>">
			<div class="promo-content">
				<img class="promo-img" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'homepage/'.$this->getValue('image_b') ?>" alt="<?php echo $this->getValue('image_b_alt'); ?>" />
				<div class="content-wrap">
					<?php echo $this->getValue('text_b'); ?>
				</div>
			</div>
		</a>
	</div>
	<div class="promo-box box-c">
		<a href="<?php echo $this->getValue('link_c'); ?>">
			<div class="promo-content">
				<img class="promo-img" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'homepage/'.$this->getValue('image_c') ?>" alt="<?php echo $this->getValue('image_c_alt'); ?>" />
				<div class="content-wrap">
					<?php echo $this->getValue('text_c'); ?>
				</div>
			</div>
		</a>
	</div>
	<div class="promo-box box-d">
		<a href="<?php echo $this->getValue('link_d'); ?>">
			<div class="promo-content">
				<img class="promo-img" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'homepage/'.$this->getValue('image_d') ?>" alt="<?php echo $this->getValue('image_d_alt'); ?>" />
				<div class="content-wrap">
					<?php echo $this->getValue('text_d'); ?>
				</div>
			</div>
		</a>
	</div>
	<div class="promo-box box-e">
		<a href="<?php echo $this->getValue('link_e'); ?>">
			<div class="promo-content">
				<img class="promo-img" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'homepage/'.$this->getValue('image_e') ?>" alt="<?php echo $this->getValue('image_e_alt'); ?>" />
				<div class="content-wrap">
					<?php echo $this->getValue('text_e'); ?>
				</div>
			</div>
		</a>
	</div>
	<div class="promo-box box-f">
		<a href="<?php echo $this->getValue('link_f'); ?>">
			<div class="promo-content">
				<img class="promo-img" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'homepage/'.$this->getValue('image_f') ?>" alt="<?php echo $this->getValue('image_f_alt'); ?>" />
				<div class="content-wrap">
					<?php echo $this->getValue('text_f'); ?>
				</div>
			</div>
		</a>
	</div>
	<div class="promo-box box-g">
		<a href="<?php echo $this->getValue('link_g'); ?>">
			<div class="promo-content">
				<img class="promo-img" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'homepage/'.$this->getValue('image_g') ?>" alt="<?php echo $this->getValue('image_g_alt'); ?>" />
				<div class="content-wrap">
					<?php echo $this->getValue('text_g'); ?>
				</div>
			</div>
		</a>
	</div>
</div>

