<?php
/**
 * @author      Sam Mahoney for Meab
 * @copyright   Copyright (C) 2016 - Meab
 */
?>

<div class="currency-selector">
    <strong>Currency</strong>
    <ul class="currency-list">
    <?php $currencies = $this->getCurrencies(); foreach ($currencies as $_code => $_name): ?>
        <li>
            <?php if($_code == $this->getCurrentCurrencyCode()): ?>
                <span class="current-currency <?php echo strtolower($_code) ?>"><?php echo Mage::app()->getLocale()->currency($_code)->getSymbol(); ?></span>
            <?php else: ?>
                <a href="<?php echo $this->getSwitchCurrencyUrl($_code) ?>" class="<?php echo strtolower($_code) ?>"><?php echo Mage::app()->getLocale()->currency($_code)->getSymbol(); ?></a>
            <?php endif; ?>
        </li>
    <?php endforeach; ?>
    </ul>
</div>