<?php
/**
 * Juvi_Gemstones extension
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 * 
 * @category       Juvi
 * @package        Juvi_Gemstones
 * @copyright      Copyright (c) 2015
 * @license        http://opensource.org/licenses/mit-license.php MIT License
 */
/**
 * Gemstone link widget template
 *
 * @category    Juvi
 * @package     Juvi_Gemstones
 * @author      Ultimate Module Creator
 */
?>
<?php $_gemstone = $this->getCurrentGemstone();?>
<?php if ($_gemstone) :?>
    <div class="gemstone-widget-link">
        <a href="<?php echo $_gemstone->getGemstoneUrl()?>"><?php echo $_gemstone->getStoneName()?></a>
    </div>
<?php endif;?>
