<?php
/**
 * Juvi_Gemstones extension
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 * 
 * @category       Juvi
 * @package        Juvi_Gemstones
 * @copyright      Copyright (c) 2015
 * @license        http://opensource.org/licenses/mit-license.php MIT License
 */
/**
 * Gemstone view widget template
 *
 * @category    Juvi
 * @package     Juvi_Gemstones
 * @author      Ultimate Module Creator
 */
?>
<?php $_gemstone = $this->getCurrentGemstone();?>
<?php if ($_gemstone) :?>
    <div class="gemstone-widget-view">
        <h3><?php echo $_gemstone->getStoneName()?></h3>
        <div>
            <div class="stone_name-widget">
                <?php echo Mage::helper('juvi_gemstones')->__('Stone Name');?>:<?php echo $_gemstone->getStoneName();?>
            </div>
            <div class="stone_origin-widget">
                <?php echo Mage::helper('juvi_gemstones')->__('Stone Origin');?>:<?php echo $_gemstone->getStoneOrigin();?>
            </div>
            <div class="stone_description-widget">
                <?php echo Mage::helper('juvi_gemstones')->__('Stone Description');?>:<?php echo $_gemstone->getStoneDescription();?>
            </div>
            <div class="stone_image-widget">
                <?php if ($_gemstone->getStoneImage()) :?>
    <img src="<?php echo Mage::helper('juvi_gemstones/gemstone_image')->init($_gemstone, 'stone_image')->resize(75);?>" alt="<?php echo $this->escapeHtml($_gemstone->getStoneName());?>" />
<?php endif;?>
            </div>

        </div>
    </div>
<?php endif;?>
