<?php
/**
 * Juvi_Gemstones extension
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 * 
 * @category       Juvi
 * @package        Juvi_Gemstones
 * @copyright      Copyright (c) 2015
 * @license        http://opensource.org/licenses/mit-license.php MIT License
 */
/**
 * Gemstone view template
 *
 * @category    Juvi
 * @package     Juvi_Gemstones
 * @author      Ultimate Module Creator
 */
?>
<?php $_gemstone = $this->getCurrentGemstone();?>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>

<div class="gemstone-featured-item">
    <?php if($_gemstone->getStoneImage()): ?>
        <div class="stone-img-wrapper">
            <img src="<?php echo Mage::helper('juvi_gemstones/gemstone_image')->init($_gemstone, 'stone_image')->resize(900,400);?>" alt="<?php echo $this->escapeHtml($_gemstone->getStoneName());?>" />
        </div>
    <?php endif; ?>
    <div class="stone-info-wrapper">
        <h2 class="name"><?php $featuredname = trim(str_replace('[featured]', '', $_gemstone->getStoneName())); echo $featuredname;?></h2>
        <div class="stone-origin"><?php echo Mage::helper('juvi_gemstones')->__('Origin: ');?><?php echo $_gemstone->getStoneOrigin();?></div>
        <br>
        <div class="stone-desc"><?php echo $_gemstone->getStoneDescription();?></div>
    </div>
</div>
